version: '3.4'

services:
  sut:
    build:
      context: .
      dockerfile: tests/config/Dockerfile
    volumes:
      - .:/app
    command: pytest
    environment:
      - PYTHONPATH=/app/ecs_deployer
